name: studyCoachEnv
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - expat=2.7.1
  - libcxx=19.1.7
  - libffi=3.4.4
  - ncurses=6.5
  - openssl=3.0.17
  - pip=26.0.1
  - python=3.10.18
  - readline=8.3
  - sqlite=3.50.2
  - tk=8.6.15
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.4.0
      - click==8.3.1
      - colorama==0.4.6
      - joblib==1.5.3
      - lxml==6.0.2
      - nltk==3.9.2
      - numpy==2.2.6
      - pandas==2.3.3
      - portalocker==3.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - regex==2026.2.19
      - rouge-score==0.1.2
      - sacrebleu==2.6.0
      - setuptools==78.1.1
      - six==1.17.0
      - tabulate==0.9.0
      - tqdm==4.67.3
      - tzdata==2025.3
      - wheel==0.45.1
